### ISSUE TITLE
syntax error near unexpected token

### ISSUE THREAD

**Issue by wangxuguo** [mattwilson1024/android-pattern-unlock#6]
When i run this script ,there are some mistakes:
.....
: command not found 
'nlock.sh: line 79: syntax error near unexpected token `{
'nlock.sh: line 79:`WakeScreen(){

How can i run this script successful?

**Comment by mattwilson1024** [comment]
What OS / environment are you running in? 

Also (maybe unrelated) but what has happened with the strange single quote in place of the 'u' in the filename?

**Comment by mattwilson1024** [comment]
Closing this issue as there has been no response and I suspect the issue may be due to the environment it was run in rather than a bug.
